In [ ]:
# corresponds to dim in Pytorch

axis = 0 # of each column
axis = 1 # of each row
# e.g. calculate the mean of each column; calculate the mean of each row


In [5]:
import numpy

# vstack
vstacked = numpy.vstack(([1, 2, 3], [3, 4, 5]))
print(vstacked)

# hstack
hstacked = numpy.hstack(([1, 2, 3], [3, 4, 5]))
print(hstacked)

[[1 2 3]
 [3 4 5]]
[1 2 3 3 4 5]


In [ ]:
# Convert a vector or indices to a one-hot encoded matrix:
import numpy


T5 = numpy.eye(6)[numpy.array([0, 1, 1, 1, 2, 2, 2, 2, 3, 5, 1])].T

T5

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

Why the above works:
You are creating an identity matrix and then taking kth row from it, depending on the index of the numpy array that you use to index it.
So, the length of the array can be anything. You just keep taking the rows of the identity matrix (eye). e.g., you can take the 0th row, then again the 0th row


In [2]:
import numpy

numpy.eye(3)[numpy.array([0, 0])]

array([[1., 0., 0.],
       [1., 0., 0.]])

In [4]:
# Vectorize function to apply function to each element of an array or a matrix 
import math

def logistic_function(z):
    return 1/(1 + math.exp(-z))

Z = numpy.random.random((1, 10))

Z2 = numpy.zeros((1, 10))

print(Z2)

vec_logistic_function = numpy.vectorize(logistic_function)

print(vec_logistic_function(Z2))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]]


In [ ]:
# Apply a function to each column separately or to each row separately, e.g. calculate mean of each column or of each row

import numpy as np

myarray = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
def myfunction(x):
    mean = numpy.mean(x)
    return numpy.array(x)/mean

print(np.apply_along_axis(numpy.mean, axis=0, arr=myarray))

# apply to each column separately
# axis = 0 => apply to each column separately
print(np.apply_along_axis(myfunction, axis=0, arr=myarray))

# apply to each row separately
# axis = 1 => apply to each row separately
print(np.apply_along_axis(myfunction, axis=1, arr=myarray))

In [ ]:
l = np.array([5, 3, 2, 4, 6, 0])
# sort ndarray indices in descending order
idx_desc = l.argsort()[::-1]
print(idx_desc)
# the list is sorted in descending order
l_desc = l[idx_desc]
print(l_desc)

# sort ndarray indices in ascending order
idx_asc = l.argsort()[::1]
# the list is sorted in ascending order
l_asc = l[idx_asc]

In [2]:
# calculate means of each column
# the result is a row-vector (tensor) of shape (1, number_of_columns) aka (1, number_of_elements_in_each_row)
import torch
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([1., 3, 4])
t3 = torch.tensor([2, 3, 3])
t4 = torch.tensor([3., 2, 5])

list = [t1, t2, t3, t4]

list_as_tensor = torch.stack(list, dim=0)

print(list_as_tensor.shape)

means_of_columns = torch.mean(list_as_tensor, dim=0)
print(means_of_columns)

means_of_rows = torch.mean(list_as_tensor, dim= 1)
print(means_of_rows)


torch.Size([4, 3])
tensor([1.7500, 2.5000, 3.7500])
tensor([2.0000, 2.6667, 2.6667, 3.3333])


In [3]:
# create tensor of random numbers from ranges

import torch

#y = torch.FloatTensor(3, 2).uniform_(-2, 2)

# another way to do this:

# (r1 - r2) * torch.rand(a, b) + r2
(-2 - 2) * torch.rand(3, 2) + 2


tensor([[ 0.7121,  1.7781],
        [ 0.0420, -1.5706],
        [-1.3416, -1.3704]])